/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "test.h"

bool_t
xdr_path (XDR *xdrs, path *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->value, 256))
		 return FALSE;
	return TRUE;
}
