/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include "test.h"

int *
func_1_svc(path *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("Function OK");

	return &result;
}
