/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TEST_H_RPCGEN
#define _TEST_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct path {
	char *value;
};
typedef struct path path;

#define TEST 0x20000001
#define TEST_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define FUNC 1
extern  int * func_1(path *, CLIENT *);
extern  int * func_1_svc(path *, struct svc_req *);
extern int test_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FUNC 1
extern  int * func_1();
extern  int * func_1_svc();
extern int test_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_path (XDR *, path*);

#else /* K&R C */
extern bool_t xdr_path ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TEST_H_RPCGEN */
